steps:
# Pull the current latest image, so we can use its cached layers.
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull',
    'gcr.io/$PROJECT_ID/lm-explorer:latest'
  ]
# Build the Docker image and tag with the current SHA and latest.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '-t', 'gcr.io/$PROJECT_ID/lm-explorer:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/lm-explorer:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/lm-explorer:latest',
    '.'
  ]
# Upload the built Docker images to Google Cloud Registry (GCR).
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/lm-explorer:$COMMIT_SHA'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/lm-explorer:latest'
  ]
# Execute a deploy of the Docker image on Kubernetes.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: '/bin/bash'
  args: [
    '.skiff/deploy.sh',
    'gcr.io/$PROJECT_ID/lm-explorer:$COMMIT_SHA'
  ]
  env: [
    'CLOUDSDK_COMPUTE_ZONE=us-west1',
    'CLOUDSDK_CONTAINER_CLUSTER=skiff-prod'
  ]
